### ISSUE TITLE
weird error on tweet/TL

### ISSUE THREAD

**Issue by ultrajae** [PrivacyDevel/nitter#14]
tried to view this tweet-
... MapsUkraine/status/1674250481848266753

get

"@MapsUkraine's account has been withheld in Germany based on local law(s). Learn more."

get the same when I even try to see his TL.

does happen on other nitter instances (ofc the 18+ don't display but all others do..)

*edit
I assume your instance is housed in Germany.. I guess that's it then,,

**Comment by PrivacyDevel** [comment]
Related to https://github.com/zedeus/nitter/issues/829#issuecomment-1521153175.
But yes, my instance is hosted in Germany, which is unfortunately causing this issue..
