### ISSUE TITLE
SEC_ERROR_UNKNOWN_ISSUER

### ISSUE THREAD

**Issue by brian6932** [PrivacyDevel/nitter#20]
![image](https://github.com/PrivacyDevel/nitter/assets/18603393/50c2d7f3-4e09-450e-acdd-8a32500769ff)

**Comment by brian6932** [comment]
Continuing results in:
![image](https://github.com/PrivacyDevel/nitter/assets/18603393/17e12819-18a1-4c90-a7c1-2293179b3d02)

**Comment by errorgurumeditation** [comment]
seems to be caused by an anti-ddos proxy
![Screenshot_20230705-195548_Bromite.jpg](https://github.com/PrivacyDevel/nitter/assets/113433581/18ad4b6a-1fd2-4df7-8ee4-a98b7371dbfc)

**Comment by ultrajae** [comment]
> seems to be caused by an anti-ddos proxy 

So, safe?

**Comment by PrivacyDevel** [comment]
It's the ddos protection that was automatically enabled by my hosting provider. The attacks should be over now and it hopefully won't happen again. Please do not ignore certificate warnings. Treat it like downtime instead.
