### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by ultrajae** [PrivacyDevel/nitter#21]
...after only maybe 4 clicks.

nm

I guess it was just timing...

I thought everything had come back but it was only a momentary blip

**Comment by PrivacyDevel** [comment]
Yes, I do currently have a very brutal rate limit in place. It's either this or no nitter at all basically thanks to Twitter's new rate limits.

If anybody just sent be a bunch of Twitter accounts that I could use I wouldn't mind increasing it again either :p

**Comment by PrivacyDevel** [comment]
> @PrivacyDevel Have you thought about buying them? There are many sites selling accounts from a few cents per unit.

I have, yes. If you could give me some links to sellers that accept cryptocurrency, I'd happily check them out.
