### ISSUE TITLE
NSFW tweets no longer available

### ISSUE THREAD

**Issue by roryyamm** [PrivacyDevel/nitter#22]
Seems the site is stuck on its SFW backup, and thus NSFW tweets all return the same thing.
![Screenshot From_2023-07-14 101446](https://github.com/PrivacyDevel/nitter/assets/24758288/918f8681-96b0-4f6e-a222-73a88b738bda)
Curiously after a certain point, this doesn't happen - older NSFW entries are shown. Is this due to caching?

**Comment by PrivacyDevel** [comment]
I changes a few things, it should hopefully be a little better now. But the rate limit for NSFW content is still quite harsh, unfortunately.

> older NSFW entries are shown. Is this due to caching?

Yes, this is because I increased the cache ttl in response to Twitter's new account based rate limits.

**Comment by inde3d** [comment]
Would it be possible to have the ID/direct url listed next to each blocked tweet on the SFW backup? I believe there's ways to get at NSFW content that way, like what fxtwitter and vxtwitter do.

**Comment by PrivacyDevel** [comment]
With the use of guest accounts this should no longer be an issue for now.
