### ISSUE TITLE
Cannot open: ./guest_accounts.json [IOError]

### ISSUE THREAD

**Issue by xbdmHQ** [PrivacyDevel/nitter#29]
```
syncio.nim(855)          readFile
Error: unhandled exception: cannot open: ./guest_accounts.json [IOError]
syncio.nim(855)          readFile
Error: unhandled exception: cannot open: ./guest_accounts.json [IOError]
syncio.nim(855)          readFile
Error: unhandled exception: cannot open: ./guest_accounts.json [IOError]
syncio.nim(855)          readFile
Error: unhandled exception: cannot open: ./guest_accounts.json [IOError]
syncio.nim(855)          readFile
Error: unhandled exception: cannot open: ./guest_accounts.json [IOError]
syncio.nim(855)          readFile
Error: unhandled exception: cannot open: ./guest_accounts.json [IOError]
syncio.nim(855)          readFile
Error: unhandled exception: cannot open: ./guest_accounts.json [IOError]
```

**Comment by PrivacyDevel** [comment]
Please checkout the pre_guest_accounts branch or ask Zedeus for a few guest accounts to fix this issue.

**Comment by xbdmHQ** [comment]
> Please checkout the pre_guest_accounts branch or ask Zedeus for a few guest accounts to fix this issue.

Can't find it

**Comment by PrivacyDevel** [comment]
It's here: https://github.com/PrivacyDevel/nitter/tree/pre_guest_accounts
Or you can just do a ``git checkout 813a71e4d33aab8a3847857444921a61b37117db`` to go to the last non guest account version and fork off of that for now.

**Comment by jve-engineering** [comment]
Hello,

I was able to get my local instance running with your latest container image and a `guest_account.json`. The account is created with the [snipplet](https://github.com/zedeus/nitter/issues/983#issuecomment-1689430618). Then I copied the json to the container with `docker cp`. Maybe this is also an approach for @xbdmHQ .

So far so good, however I noticed one thing, your instances show posts for e.g. `noclador/media` where mine and also nitter.net only show "No items found". 

What is the secret sauce with your instance?

**Comment by PrivacyDevel** [comment]
@jve-engineering I think it depends on what country you are accessing the Twitter servers from. My instance didn't show age restricted content with the newest changes either, initially.

Then I started using a proxy from another country and now everything works.

From what I observed, it looks like France and the Netherlands  are more restricted than the Czech Republic, for example.

**Comment by xbdmHQ** [comment]
Yeah, someone can bother hosting it now or just use the official ```nitter.net``` domain instead. I will not host this anymore and since it require more time and effort.

**Comment by xbdmHQ** [comment]
@PrivacyDevel Maybe put an example guest_accounts.json in the repo to fix confusion

**Comment by slikie** [comment]
Can't seem to get it working by mounting guest_accounts.json in docker-compose. 
```
volumes:
  - ./guest_accounts.json:/src/guest_accounts.json:Z,ro
```

**Comment by PrivacyDevel** [comment]
@slikie, maybe it works with @jve-engineering suggesting above?

**Comment by xbdmHQ** [comment]
Oh i forgot about this issue. I have resolved my issue with this sense then, If anyone still having problems getting their public instance up and running. I will have my configuration fork [here](https://github.com/WhateverItWorks/NitterX).

**Comment by slikie** [comment]
> @slikie, maybe it works with @jve-engineering's suggesting above?

It would work, but it doesn't seem to be the right approach, as the accounts expire fairly frequently(around 1 months).

Even with `docker run  -v $(pwd)/guest_accounts.json:/src/guest_accounts.json  -v $(pwd)/nitter.conf:/src/nitter.conf -d --network host ghcr.io/privacydevel/nitter:master`  It still gets the same error of `SIGSEGV: Illegal storage access. (Attempt to read from nil?)`. 

Maybe this is more of a upstream issue though.

**Comment by PrivacyDevel** [comment]
> It would work, but it doesn't seem to be the right approach, as the accounts expire fairly frequently(around 1 months).

The guest_accounts.json file needs to be replaced every 30 days somehow, yes. There is no way around this really with the current solution.

**Comment by slikie** [comment]
It would be a hassle to manage inside docker but way less annoyance with bind mounts. Please merge upstream as it fixes this issue.
