### ISSUE TITLE
Not items Found when I searched anything

### ISSUE THREAD

**Issue by geol** [PrivacyDevel/nitter#3]
![9DD80215-C54D-495E-99C7-0F1619136299](https://user-images.githubusercontent.com/2117430/234094392-536f50d4-4967-423a-b655-4690e929cf1f.jpeg)
I deployed this to my own server, nginx proxy passby 127.0.0.1:8080, when I visit the web page and search any account, I got this. I wondered if I missed something in the conf file.

**Comment by PrivacyDevel** [comment]
Did you set your values for the following fields and remove the "#" at the beginning of those lines?
- cookieHeader
- xCsrfToken

It should work after you've done that. Unauthenticated search does currently not work in this fork because the new commit that fixed it introduces bugs of its own. See: https://github.com/PrivacyDevel/nitter/pull/2

**Comment by geol** [comment]
do I need them both? my web browser only got me cookie header and auth token. I'll try how to get xcrftoken, and thank you so much!

**Comment by PrivacyDevel** [comment]
Yes, you need both. You can see it in the request headers in the network tab, if you press F12.

**Comment by geol** [comment]
Is it possible to get those on a android/ios mobile web browser?

**Comment by PrivacyDevel** [comment]
Maybe? If there are some kind of developer tools, you might be able to find it there. But I don't really know tbh.

**Comment by geol** [comment]
Thank you so much for help!

**Comment by geol** [comment]
could u close this issue please? I use mobile web browser and can not do this.

**Comment by PrivacyDevel** [comment]
On Android you could install the Kiwi browser and use the developer tools there to get the x-csrf-token header. I just checked. I don't know about other browsers tho.

**Comment by DrSocket** [comment]
Seems the graphql endpoints have been shutdown as well, are you still working on merging it here or do you recon there's no point anymore?

**Comment by PrivacyDevel** [comment]
I am probably going to merge it sometime once that thread bug has been fixed that's mentioned in #2. But yeah, it's a shame that unauthenticated search is broken again for now..

**Comment by geol** [comment]
My sever seems work fine. I sub the rss from the server, I have noticed some twit didn't show up, but I don't care that much. Thank you so much for your work.

**Comment by psegovias** [comment]
I put the cookieHeader , auth_token and xCsrfToken but didnt work, still the msg "No items found"

**Comment by PrivacyDevel** [comment]
> I put the cookieHeader , auth_token and xCsrfToken but didnt work, still the msg "No items found"

Did you also supply your ct0 cookie value there? In the same kind of format as in the example? And did you remove the '#' at the beginning of those two lines? Because if you did,  profile pages should be working.

If you want to see nsfw search results you have to do [this](https://github.com/zedeus/nitter/issues/829#issuecomment-1510067533) as well.

**Comment by psegovias** [comment]
> 

I setup like this:

`cookieHeader = "ct0=8d0b150c5cb49c35c5d5101882XXXXXXXXX	; auth_token=486fbXXXXXXX" # authentication cookie of a logged in account, required for the likes tab and NSFW content`
`xCsrfToken = "8d0b150c5XXXXXXXXXX" # required for the likes tab and NSFW content
`

And console show only this:


`[tokens] added new token to pool`
`[tokens] added new token to pool`
`[tokens] added new token to pool`
`[tokens] added new token to pool`
`[tokens] added new token to pool`

i create another folder apart from where the official version of nitter was running.

**Comment by psegovias** [comment]
> > I put the cookieHeader , auth_token and xCsrfToken but didnt work, still the msg "No items found"
> 
> Did you also supply your ct0 cookie value there? In the same kind of format as in the example? And did you remove the '#' at the beginning of those two lines? Because if you did, profile pages should be working.
> 
> If you want to see nsfw search results you have to do [this](https://github.com/zedeus/nitter/issues/829#issuecomment-1510067533) as well.

I setup like this:

`cookieHeader = "ct0=8d0b150c5cb49c35c5d5101882XXXXXXXXX	; auth_token=486fbXXXXXXX" # authentication cookie of a logged in account, required for the likes tab and NSFW content`
`xCsrfToken = "8d0b150c5XXXXXXXXXX" # required for the likes tab and NSFW content
`

And console show only this:


`[tokens] added new token to pool`
`[tokens] added new token to pool`
`[tokens] added new token to pool`
`[tokens] added new token to pool`
`[tokens] added new token to pool`

i create another folder apart from where the official version of nitter was running.

**Comment by PrivacyDevel** [comment]
Do you see the "likes" tab on a twitter profile page? Try to remove the white space between the ct0 token and the ";". And this is in the nitter.conf file in the working directory, right?

**Comment by psegovias** [comment]
Deleting the white space did the work!

What is the ratelimit with an account?

**Comment by PrivacyDevel** [comment]
Great! I'm actually not even sure about that myself tbh. But Twitter even tells you in the response headers iirc.

**Comment by psegovias** [comment]
Maybe a group of accounts is better for this? something that can be randomized every time the instance starts to avoid ratelimit?

**Comment by PrivacyDevel** [comment]
Depending on how much you intend to use it that would make sense, yes. I am basically [doing that already](https://github.com/zedeus/nitter/issues/829#issuecomment-1517125707) btw.

**Comment by psegovias** [comment]
> Depending on how much you intend to use it that would make sense, yes. I am basically [doing that already](https://github.com/zedeus/nitter/issues/829#issuecomment-1517125707) btw.

nice, im trying the same thing, i already have the cookieHeader and auth_token, working to get xCsrfToken
