### ISSUE TITLE
Instance has been rate limited for 1-2 days

### ISSUE THREAD

**Issue by Chrisatsinnoh** [PrivacyDevel/nitter#32]
Two days ago, I was browsing the privacydev instance to access Twitter accounts without restrictions. However, it got to a point where I was hit with a “Instance has been rate limited”, and assuming it was a temporary message, I stopped using said instance and went to bed, thinking it was going to be resolved, but it has not the next day I woke up. The instance remains “rate limited” as of recently today. Should I keep waiting?

**Comment by PrivacyDevel** [comment]
I merged in the newest changes from the upstream nitter project and now it's working again. I hope it's not a reoccurring issue but I'll deal with that when it happens. I apologize for the inconvenience.

**Comment by vehosah** [comment]
It still limited 😔
