### ISSUE TITLE
RSS feeds don't include the port in the URLs

### ISSUE THREAD

**Issue by quickwick** [PrivacyDevel/nitter#37]
I self-host a private Nitter instance just for me.

I just switched from the pre_guest_accounts branch to master, and everything is mostly working, except RSS feeds are broken. The port (:8080) is no longer included in any of the nitter URLs. So image thumbnails won't display, and if I try to open a feed item in my browser from my rss reader, it won't load. But if I manually edit the URL in the browser address bar to add :8080, then it loads.

Is this an issue with this fork, or should I post this in the main zedeus/nitter Issues?

**Comment by PrivacyDevel** [comment]
I can't think of anything I've changed that would cause those kinds of issues. It would probably be a good idea to ideally test that with the Zedeus' version first and then report it there if the issue persists.

**Comment by quickwick** [comment]
Yeah, I ended up just adding the :8080 manually into the hostname in nitter.conf, and that seems to have done the trick.
