### ISSUE TITLE
PrivacyDev is broken

### ISSUE THREAD

**Issue by Chrisatsinnoh** [PrivacyDevel/nitter#39]
When I went to Nitter's PrivacyDev instance to look over various accounts without a twitter account, I ran into some issues.

Images and videos are broken, I get a 500 internal server error when I check the media or replies of some accounts, the instance is rate limited message is also involved as well, replies are not sometimes shown, etc.

There could be more issues than the ones I am recalling at the time of writing; it happened last night.

**Comment by PrivacyDevel** [comment]
Thank you for your error report. Those issues should now have been solved. Please let me know if there is still something that has not been addressed.
