### ISSUE TITLE
Retweet URLs don't display properly

### ISSUE THREAD

**Issue by errorgurumeditation** [PrivacyDevel/nitter#5]
Instead of showing the tweet with "x retweeted" above, it says "RT @xyz: abcde...". It also doesn't display attached media.

Example: https://nitter.privacydev.net/ditzy_bunny/status/1634535003597033472

**Comment by errorgurumeditation** [comment]
may be related: zedeus/nitter#801

**Comment by PrivacyDevel** [comment]
This seems to be fixed now. Or do you still notice it somewhere?

**Comment by errorgurumeditation** [comment]
Seems to be fixed, thank you so much! Closing this now
