### ISSUE TITLE
Use of proxy needed if using multiple accounts?

### ISSUE THREAD

**Issue by muhitrhn** [PrivacyDevel/nitter#55]
Do I need to use proxy if I am using multiple twitter accounts to faciliate a private instance? Or I can just continue without using proxy?

**Comment by muhitrhn** [comment]
@PrivacyDevel @rotorot0 @cmj anyone?

**Comment by rotorot0** [comment]
I haven't run into any issues regarding any of my accounts used for my instance, so AFAIK, no.

**Comment by muhitrhn** [comment]
> I haven't run into any issues regarding any of my accounts used for my instance, so AFAIK, no.

How many accounts do you use in your instance if I may ask please?

**Comment by rotorot0** [comment]
> > I haven't run into any issues regarding any of my accounts used for my instance, so AFAIK, no.
> 
> How many accounts do you use in your instance if I may ask please?

Five accounts. Which seems to be enough for my private instance.

**Comment by muhitrhn** [comment]
> > > I haven't run into any issues regarding any of my accounts used for my instance, so AFAIK, no.
> > 
> > 
> > How many accounts do you use in your instance if I may ask please?
> 
> Five accounts. Which seems to be enough for my private instance.

Thank you very much! Also could you please tell me if any of your accounts being used face issues like getting temporary blocked?

**Comment by rotorot0** [comment]
> > > > I haven't run into any issues regarding any of my accounts used for my instance, so AFAIK, no.
> > > 
> > > 
> > > How many accounts do you use in your instance if I may ask please?
> > 
> > 
> > Five accounts. Which seems to be enough for my private instance.
> 
> Thank you very much! Also could you please tell me if any of your accounts being used face issues like getting temporary blocked?

Not from what I've seen. One of the accounts I use with nitter, I use it quite regularly on Twitter itself and no temp blocks.

**Comment by muhitrhn** [comment]
Thank you very much for your help @rotorot0 ! I'm hoping even if I use more than 10 accounts, I won't need to use proxy as that will increase response time and I need the response to be within exactly 3 seconds.
