### ISSUE TITLE
[Question] How do I use the OAuth script when running nitter as a docker comtainer

### ISSUE THREAD

**Issue by back-lacking** [PrivacyDevel/nitter#58]
Basically what the title asks. 
How do i use the OAuth script when Nitter is being ran as a docker container? my homelab consists of docker services and i ve set up things around things being docker.

**Comment by back-lacking** [comment]
nevermind figured it out. probably gonna make a commit to the readme to better clarify what to do. along with changes to docker compose and oauth script
i had to add square brackets to the beginning and end of the text file. and then add the json file as a volume to `/src/guest_accounts.json`

**Comment by ghost** [comment]
If you can go into more detail here, I'd appreciate it.

**Comment by back-lacking** [comment]
> If you can go into more detail here, I'd appreciate it.

https://github.com/PrivacyDevel/nitter/pull/59 here is the pr i made for this. includes changes to docker compose and the change i amde to the script
