### ISSUE TITLE
Docker Image?

### ISSUE THREAD

**Issue by mephisto3478** [PrivacyDevel/nitter#6]
Hey!
Thanks for your effort in re-enabling 18+ Posts.
I would like to be independent of public instances and host my own, as I already do with the [official nitter docker image](https://hub.docker.com/r/zedeus/nitter).
Could you perhaps create a docker image for your fork as well?

**Comment by PrivacyDevel** [comment]
I am considering it, yes.

**Comment by mephisto3478** [comment]
I would greatly appreciate it :)

**Comment by Mozi71** [comment]
> I am considering it, yes.

I'm sorry to say that I failed to compile the Docker image by myself. If you could provide a Docker image that supports browsing R18 content along with its address, I would greatly appreciate it.
