### ISSUE TITLE
[Feature request] Ability to view post interactions (likes, retweets, quote tweets)

### ISSUE THREAD

**Issue by FoxBlocks** [PrivacyDevel/nitter#7]
First off, I'd like to thank you for making this fork! It's been an incredibly valuable resource to me for searching Twitter after search was disabled for guests.

Here's my request. Since this fork uses credentials to allow search and show blocked posts, then theoretically it could also show the names of users who like and retweet a post (like on Twitter when you click the "(#) Likes" and "(#) Retweets" texts). If you could add that functionality, it would make this fork even more valuable.

I have no experience with the programming that goes into this, so I don't know how hard it would be to implement, but it would make for a great feature.

**Comment by PrivacyDevel** [comment]
Thank you for this great suggestion! I'm not that sure how I would best integrate that feature into nitter yet but I did just add the likes and retweets feature it to my own Twitter front-end [yitter](https://github.com/PrivacyDevel/yitter) if you want to use that for the time being. :)
You can check the list of users by clicking on the like or the retweet counter or icon under a tweet.

**Comment by FoxBlocks** [comment]
Oh, nice! It works perfectly, even on posts marked as adult! I can see that yitter is very bare-bones compared to nitter, so I'll use both interchangeably to suit my needs. Thank you so much!

**Comment by FoxBlocks** [comment]
UPDATE: It won't show me quote tweets. This is still very useful otherwise!

**Comment by PrivacyDevel** [comment]
> UPDATE: It won't show me quote tweets. This is still very useful otherwise!

Yeah, quote retweets aren't implemented yet. Implementing the likes and retweet user list was fairly easy and they both work very similarly. Quote retweets seem to work by performing a search in the background. Will probably implement that sometime as well tho and keep you updated on this issue here as soon as I do.

**Comment by FoxBlocks** [comment]
Ah, okay. I'll wait! Thanks for everything so far!

**Comment by PrivacyDevel** [comment]
Added quote retweet list support in https://github.com/PrivacyDevel/yitter/commit/6ceeff93d2e708062e20a1f23c520e04cd045867. That one was surprisingly the easiest of them all and does not even require an account as long as you're able to make searches without one, that is.

**Comment by FoxBlocks** [comment]
Clicking the button gives me a 500 Internal Server Error on yitter, but I'm able to take the search term it tries to use, and search it on nitter.

Okay, I'm satisfied now! Thanks again for everything!

**Comment by PrivacyDevel** [comment]
Found the issue and fixed it. Thank you for letting me know!

**Comment by PrivacyDevel** [comment]
@FoxBlocks In case you're interested, you can now see who somebody follows and is followed by on yitter as well. :)

**Comment by PrivacyDevel** [comment]
And I added the retweeters and favoriters user lists to nitter now as well.
See my PR: zedeus/nitter#897
And I also deployed it on my instance. :)

**Comment by FoxBlocks** [comment]
Wow, you've gone above and beyond! Thanks for adding a follower view as well, and thanks again for everything else!

**Comment by PrivacyDevel** [comment]
You're very welcome!

**Comment by PrivacyDevel** [comment]
Added the followers + following user list to nitter as well now :)
